language: java

script:
	- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

jdk:
	- oraclejdk8
  
cache:
    directories:
    - $HOME/.m2
    
after_success:
	- mvn coveralls:report